import type { Metadata } from "next";
import {Lato } from 'next/font/google';
import "./globals.css";
import Footer from "@/Components/Footer";
import TopBar from "@/Components/Topbar";
import Header from "@/Components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'], 
  variable: '--font-lato',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={` ${lato.variable}`}><TopBar/>
      <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
